name: Cleanup

on:
  schedule:
    - cron: '0 0 * * 1'  # Läuft jeden Montag um Mitternacht

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          older-than: 7
